# Generated by Django 3.2.3 on 2021-12-04 21:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('barcode', models.CharField(blank=True, max_length=30, null=True, verbose_name='Codigo de barras')),
                ('title', models.CharField(max_length=40, verbose_name='Titulo')),
                ('availability', models.BooleanField(null=True, verbose_name='Disponibilidad')),
                ('image', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Imagen')),
                ('Info', models.TextField(blank=True, null=True, verbose_name='Informacion')),
            ],
            options={
                'verbose_name': 'Libro',
                'db_table': 'Libro',
            },
        ),
        migrations.CreateModel(
            name='Cliient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observation', models.TextField(blank=True, null=True, verbose_name='Comentario')),
                ('fk_id_user', models.ForeignKey(default=6, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'cliente',
                'db_table': 'clientes',
            },
        ),
        migrations.CreateModel(
            name='DocumentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomb_type_document', models.CharField(max_length=25, verbose_name='Tipo de documento')),
                ('acronym_doc', models.CharField(max_length=10, verbose_name='Siglas')),
            ],
            options={
                'verbose_name': 'Tipo de Documento',
                'verbose_name_plural': 'Tipos de Documentos',
                'db_table': 'Tipo de documento',
            },
        ),
        migrations.CreateModel(
            name='Editorial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_editorial', models.CharField(max_length=45, verbose_name='Editorial')),
            ],
            options={
                'verbose_name': 'Editorial',
                'verbose_name_plural': 'Editoriales',
                'db_table': 'Editorial',
            },
        ),
        migrations.CreateModel(
            name='LogError',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description_error', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'log_error',
            },
        ),
        migrations.CreateModel(
            name='ServerMail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mail', models.EmailField(blank=True, max_length=254, null=True)),
            ],
            options={
                'db_table': 'server_mail',
            },
        ),
        migrations.CreateModel(
            name='tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_tag', models.CharField(max_length=30, verbose_name='Etiquta')),
            ],
            options={
                'verbose_name': 'Etiquta',
                'db_table': 'Etiqutas',
            },
        ),
        migrations.CreateModel(
            name='Writer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_writer', models.CharField(max_length=50, verbose_name='Autor')),
            ],
            options={
                'verbose_name': 'Autor',
                'verbose_name_plural': 'Autores',
                'db_table': 'Autores',
            },
        ),
        migrations.CreateModel(
            name='Useer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_user', models.CharField(max_length=25, verbose_name='Numero de documento')),
                ('address', models.CharField(max_length=20, verbose_name='Dirección')),
                ('cell_phone', models.CharField(max_length=25, verbose_name='Teléfono')),
                ('fk_type_document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prestamos.documenttype', verbose_name='Tipo de Documento')),
                ('user', models.OneToOneField(default=6, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Usuario',
                'db_table': 'Usuarios',
            },
        ),
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_loan', models.DateField(verbose_name='Fecha de préstamo')),
                ('return_date', models.DateField(verbose_name='Fecha de devolucion')),
                ('state', models.CharField(choices=[('A', 'Activo'), ('F', 'Finalizado'), ('R', 'Retrazo')], max_length=12, null=True, verbose_name='Estado')),
                ('coment', models.TextField(blank=True, null=True, verbose_name='Comentario')),
                ('fk_book', models.ManyToManyField(to='prestamos.Book', verbose_name='Libro')),
                ('fk_id_client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prestamos.cliient', verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Préstamo',
                'db_table': 'Prestamos',
            },
        ),
        migrations.AddField(
            model_name='book',
            name='fk_editorial',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prestamos.editorial', verbose_name='Editorial'),
        ),
        migrations.AddField(
            model_name='book',
            name='fk_tag',
            field=models.ManyToManyField(to='prestamos.tag', verbose_name='Etiqueta(s)'),
        ),
        migrations.AddField(
            model_name='book',
            name='fk_writer',
            field=models.ManyToManyField(to='prestamos.Writer', verbose_name='Escritor(es)'),
        ),
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fk_id_user', models.ForeignKey(default=6, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Administrador',
                'verbose_name_plural': 'Administradores',
                'db_table': 'Administradores',
            },
        ),
    ]
