# Generated by Django 3.2.3 on 2021-05-17 00:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observation', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'cliient',
            },
        ),
        migrations.CreateModel(
            name='DocumentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomb_type_document', models.CharField(max_length=25)),
                ('acronym_doc', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'document_type',
            },
        ),
        migrations.CreateModel(
            name='Editorial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_editorial', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'Editorial',
            },
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_genre', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'genre',
            },
        ),
        migrations.CreateModel(
            name='LogError',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description_error', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'log_error',
            },
        ),
        migrations.CreateModel(
            name='ServerMail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mail', models.EmailField(blank=True, max_length=254, null=True)),
            ],
            options={
                'db_table': 'server_mail',
            },
        ),
        migrations.CreateModel(
            name='Writer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_writer', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'writer',
            },
        ),
        migrations.CreateModel(
            name='Useer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_user', models.IntegerField(max_length=20)),
                ('first_name', models.CharField(max_length=15)),
                ('sec_name', models.CharField(blank=True, max_length=15, null=True)),
                ('surname', models.CharField(max_length=15)),
                ('sec_surname', models.CharField(blank=True, max_length=15, null=True)),
                ('password_ad', models.CharField(max_length=12)),
                ('email', models.EmailField(max_length=111)),
                ('address', models.CharField(max_length=20)),
                ('cell_phone', models.BigIntegerField()),
                ('fk_type_document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prestamos.documenttype')),
            ],
            options={
                'db_table': 'useer',
            },
        ),
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_loan', models.DateTimeField(auto_now=True)),
                ('return_date', models.DateField()),
                ('current_state', models.TextField()),
                ('coment', models.TextField(blank=True, null=True)),
                ('fk_id_client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prestamos.cliient')),
            ],
            options={
                'db_table': 'loan',
            },
        ),
        migrations.AddField(
            model_name='cliient',
            name='fk_id_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prestamos.useer'),
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('barcode', models.CharField(blank=True, max_length=30, null=True)),
                ('title', models.CharField(max_length=40)),
                ('availability', models.CharField(choices=[('D', 'disponible'), ('N', 'no disponible')], max_length=14)),
                ('coments', models.TextField(blank=True, null=True)),
                ('fk_editorial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prestamos.editorial')),
            ],
            options={
                'db_table': 'book',
            },
        ),
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fk_id_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prestamos.useer')),
            ],
            options={
                'db_table': 'admin',
            },
        ),
    ]
