# Generated by Django 3.2.3 on 2021-05-19 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prestamos', '0002_alter_useer_document_user'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='cliient',
            table='client',
        ),
    ]
