# Generated by Django 3.2.3 on 2021-05-20 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prestamos', '0004_auto_20210519_0921'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='imagen'),
        ),
    ]
