# Generated by Django 3.2.3 on 2021-05-21 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prestamos', '0005_book_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='documenttype',
            options={'verbose_name': 'tip de documento'},
        ),
    ]
