# Generated by Django 3.2.3 on 2021-05-21 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prestamos', '0006_alter_documenttype_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='admin',
            options={'verbose_name': 'Administrador'},
        ),
        migrations.AlterModelOptions(
            name='book',
            options={'verbose_name': 'Libro'},
        ),
        migrations.AlterModelOptions(
            name='cliient',
            options={'verbose_name': 'cliente'},
        ),
        migrations.AlterModelOptions(
            name='documenttype',
            options={'verbose_name': 'tipo de documento'},
        ),
        migrations.AlterModelOptions(
            name='editorial',
            options={'verbose_name': 'Editorial'},
        ),
        migrations.AlterModelOptions(
            name='genre',
            options={'verbose_name': 'Genero'},
        ),
        migrations.AlterModelOptions(
            name='loan',
            options={'verbose_name': 'Prestamo'},
        ),
        migrations.AlterModelOptions(
            name='useer',
            options={'verbose_name': 'Usuario'},
        ),
        migrations.AlterModelOptions(
            name='writer',
            options={'verbose_name': 'Autor'},
        ),
    ]
