# Generated by Django 3.2.3 on 2021-05-22 17:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('prestamos', '0008_auto_20210521_0853'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='availability',
            field=models.CharField(choices=[('D', 'Disponible'), ('N', 'No disponible')], max_length=14, verbose_name='Disponivilidad'),
        ),
        migrations.AlterField(
            model_name='book',
            name='fk_editorial',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prestamos.editorial', verbose_name='Editorial'),
        ),
        migrations.AlterField(
            model_name='book',
            name='fk_genre',
            field=models.ManyToManyField(to='prestamos.Genre', verbose_name='Genero(s)'),
        ),
        migrations.AlterField(
            model_name='book',
            name='fk_writer',
            field=models.ManyToManyField(to='prestamos.Writer', verbose_name='Escritor(es)'),
        ),
    ]
