# Generated by Django 3.2.3 on 2021-05-27 22:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('prestamos', '0009_auto_20210522_1220'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='documenttype',
            options={'verbose_name': 'Tipo de Documento', 'verbose_name_plural': 'Tipos de Documentos'},
        ),
        migrations.AlterModelOptions(
            name='genre',
            options={'verbose_name': 'Género'},
        ),
        migrations.AlterModelOptions(
            name='loan',
            options={'verbose_name': 'Préstamo'},
        ),
        migrations.AddField(
            model_name='loan',
            name='fk_book',
            field=models.ManyToManyField(to='prestamos.Book', verbose_name='Libro'),
        ),
        migrations.AlterField(
            model_name='admin',
            name='fk_id_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prestamos.useer', verbose_name='Usuario'),
        ),
        migrations.AlterField(
            model_name='book',
            name='availability',
            field=models.BooleanField(null=True, verbose_name='Disponibilidad'),
        ),
        migrations.AlterField(
            model_name='book',
            name='fk_genre',
            field=models.ManyToManyField(to='prestamos.Genre', verbose_name='Género(s)'),
        ),
        migrations.AlterField(
            model_name='book',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Imagen'),
        ),
        migrations.AlterField(
            model_name='cliient',
            name='fk_id_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prestamos.useer', verbose_name='Usuario'),
        ),
        migrations.AlterField(
            model_name='genre',
            name='name_genre',
            field=models.CharField(max_length=30, verbose_name='Género'),
        ),
        migrations.AlterField(
            model_name='loan',
            name='current_state',
            field=models.BooleanField(verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='loan',
            name='date_loan',
            field=models.DateTimeField(auto_now=True, verbose_name='Fecha de préstamo'),
        ),
        migrations.AlterField(
            model_name='loan',
            name='fk_id_client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prestamos.cliient', verbose_name='Usuario'),
        ),
        migrations.AlterField(
            model_name='useer',
            name='address',
            field=models.CharField(max_length=20, verbose_name='Dirección'),
        ),
        migrations.AlterField(
            model_name='useer',
            name='cell_phone',
            field=models.BigIntegerField(verbose_name='Teléfono'),
        ),
        migrations.AlterField(
            model_name='useer',
            name='fk_type_document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prestamos.documenttype', verbose_name='Tipo de Documento'),
        ),
        migrations.AlterField(
            model_name='useer',
            name='password_ad',
            field=models.CharField(max_length=20, verbose_name='Contraseña'),
        ),
    ]
