# Generated by Django 3.2.3 on 2021-10-20 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prestamos', '0011_alter_useer_document_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_genre', models.CharField(max_length=30, verbose_name='Etiquta')),
            ],
            options={
                'verbose_name': 'Etiqutas',
                'db_table': 'Etiquta',
            },
        ),
        migrations.RemoveField(
            model_name='book',
            name='coments',
        ),
        migrations.RemoveField(
            model_name='book',
            name='fk_genre',
        ),
        migrations.AddField(
            model_name='book',
            name='Info',
            field=models.TextField(blank=True, null=True, verbose_name='Informacion'),
        ),
        migrations.DeleteModel(
            name='Genre',
        ),
        migrations.AddField(
            model_name='book',
            name='fk_tag',
            field=models.ManyToManyField(to='prestamos.tag', verbose_name='Etiqueta(s)'),
        ),
    ]
