# Generated by Django 3.2.3 on 2021-10-20 01:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prestamos', '0012_auto_20211019_1954'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tag',
            options={'verbose_name': 'Etiquta'},
        ),
        migrations.AlterModelTable(
            name='tag',
            table='Etiqutas',
        ),
    ]
