# Generated by Django 3.2.3 on 2021-10-20 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prestamos', '0013_auto_20211019_2016'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loan',
            name='current_state',
        ),
        migrations.AddField(
            model_name='loan',
            name='state',
            field=models.BooleanField(null=True, verbose_name='Estado'),
        ),
    ]
