# Generated by Django 3.2.3 on 2021-10-20 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prestamos', '0014_auto_20211020_1439'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='state',
            field=models.CharField(choices=[('A', 'Activo'), ('F', 'Finalizado'), ('R', 'Retrazo')], max_length=12, null=True, verbose_name='Estado'),
        ),
    ]
