# Generated by Django 3.2.3 on 2021-11-25 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prestamos', '0016_auto_20211123_1521'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='date_loan',
            field=models.DateField(verbose_name='Fecha de préstamo'),
        ),
    ]
